config/routes.rb
ShopBunny::Engine.routes.draw do
  resource :cart, :only => [:show, :update] do
    get :add_item, :as => 'add_item_to'
    get :remove_item, :as => 'remove_item_from'
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  attr_accessor :coupon_code
  has_many :cart_items, :dependent => :destroy
  has_many :coupon_uses, :dependent => :destroy
  has_many :coupons, :through => :coupon_uses
  accepts_nested_attributes_for :cart_items, :allow_destroy => true 
  before_save :update_coupons
  attr_accessible :coupon_code, :cart_items_attributes
  validate :coupon_code_must_be_valid    
  
  def items
    self.cart_items
  end
  
  def item_count
    self.cart_items.inject(0) {|sum,e| sum += e.quantity}
  end
  
  def shipping_costs
    return 0 if coupons.any?(&:removes_shipping_cost)
    shipping_cost_calculator.costs_for(self)
  end

  # Calculates the sum of all cart_items, excluding the coupons discount!
  def item_sum
    self.cart_items.inject(0) {|sum,e| sum += e.quantity*e.item.price}
  end

  # Calculates the total sum and applies the coupons discount! 
  def total
    sum = item_sum

    absolute_discount = coupons.sum(:discount_credit)
    relative_discount = coupons.inject(1) {|s,coupon| s * coupon.discount_percentage }

    sum -= absolute_discount
    sum *= relative_discount
    
    sum += shipping_costs
    
    [0, sum].max
  end
  
  #increases the quantity of an article. creates a new one if it doesn't exist
  def add_item(item,options = {})
    options[:quantity] ||= 1
    cart_item = self.cart_items.find_or_create_by_item_id(item.id)
    cart_item.quantity += options[:quantity]
    cart_item.save!
    self.reload
    cart_item
  end
  
  #removes a quantity of an article specified by :article_id, returns nil if no article has been found
  def remove_item(item,options = {})
    cart_item = self.cart_items.find_by_item_id(item)
    
    options[:quantity] ||= cart_item.quantity
    if cart_item
      cart_item.quantity -= options[:quantity]
      cart_item.save!
      self.reload
    end
    cart_item
  end

  #sets the quantity of an article specified by :article_id, returns nil if no article has been found
  def update_item(item,options)
     cart_item = self.cart_items.find_by_item_id(item)
    if cart_item
      cart_item.quantity = options[:quantity]
      cart_item.save!
      self.reload
    end
    cart_item
  end
  
  def shipping_cost_calculator
    ShopBunny.shipping_cost_calculator
  end
  
  # Returns the class/model of the items you can buy. (Products)
  def item_model
    ShopBunny.item_model_class_name.constantize
  end
  
  # Make
  def as_json(options={})
    { 
      :cart => attributes.
      merge(
        :cart_items => cart_items.as_json,                
        :item_count => item_count,
        :coupons => coupons.as_json,
        :item_sum => item_sum,
        :shipping_costs => shipping_costs,
        :total => total
      )
    }
  end
  
  private
  
  def update_coupons
    Array(@coupon_code).each { |code|
      coupon = Coupon.find_by_code(code)
      coupons << coupon if coupon
    }
  end
  
  def coupon_code_must_be_valid
    Array(@coupon_code).each { |code|
      coupon = Coupon.find_by_code(code)
      if coupon.nil?
        errors.add(:coupon_code, "is unknown")
      elsif coupon.expired?
        errors.add(:coupon_code, "is expired")
      end
    }
  end
end

app/models/shop_bunny/cart_item.rb
class ShopBunny::CartItem < ActiveRecord::Base
  belongs_to :cart
  # belongs_to :item, :class_name => ShopBunny.item_model_class_name
  
  validates_presence_of :cart_id
  # validates_presence_of :item_id
  validates_numericality_of :quantity
  
  before_validation :set_default_quantity
  after_update :destroy_if_empty
  after_save :update_automatic_coupons
  after_destroy :update_automatic_coupons

  def total_price
    quantity * item.price
  end
  
  def item=(new_item)
    write_attribute(:raw_item, (new_item.respond_to?(:shop_bunny_json_attributes) ? new_item.shop_bunny_json_attributes : new_item.attributes).to_json)
    @parsed_raw_item = nil
    new_item
  end
  
  def item
    return nil unless raw_item
    unless @parsed_raw_item
      json = JSON.parse(raw_item)
        
      if json
        @parsed_raw_item = ShopBunny.item_model_class_name.constantize.new(json)
        @parsed_raw_item.id = json['id']
      end
    end
    @parsed_raw_item
  end

  def as_json(options={})
    {
      :quantity => quantity,
      :id => item.id
    }
  end

  private

  def update_automatic_coupons
    cart.update_automatic_coupons! if cart
  end

  def set_default_quantity
    self.quantity ||= 0
  end
  
  def destroy_if_empty
    self.destroy if quantity.to_i <= 0
  end
  
  def self.include_enhancements
    ShopBunny.cart_item_enhancements.each do |enhancement|
      include enhancement
    end
  end
  
  ShopBunny.cart_item_enhancements.each do |enhancement|
    include enhancement
  end
end

app/models/shop_bunny/coupon.rb
class ShopBunny::Coupon < ActiveRecord::Base
  InvalidEvent = Class.new(NoMethodError)
  has_many :coupon_uses, :dependent => :destroy, :class_name => 'ShopBunny::CouponUse'
  has_many :carts, :through => :coupon_uses
  belongs_to :bonus_article, :class_name => ShopBunny.item_model_class_name

  validates_presence_of :code
  validates_uniqueness_of :code
  validates_presence_of :title

  after_initialize { self.state ||= 'inactive' }

  scope :valid, lambda {{:conditions => ['(coupons.valid_from IS NULL OR coupons.valid_from <= ?) AND (coupons.valid_until IS NULL OR coupons.valid_until >= ?) AND coupons.state = ?', Time.now, Time.now, 'active']}}
  scope :automatically_added_over, lambda {|value| {:conditions => ['value_of_automatic_add <= ?', value]}}

  def expired?
    not_yet_valid? || has_expired?
  end

  def not_yet_valid?
    Time.now < self.valid_from if self.valid_from 
  end

  def has_expired?
    Time.now > self.valid_until if self.valid_until 
  end

  def used_up?
    max_uses && max_uses <= coupon_uses.count
  end

  def redeemable?
    !not_yet_valid? && !has_expired? && state == 'active' && !used_up?
  end

  def activate!
    raise InvalidEvent unless state == 'inactive'
    self.state = 'active'
    save!
  end

  def redeem!
    raise InvalidEvent unless redeemable?
    self.state = 'redeemed'
    save!
  end

  #check ifthe cart's sum exceeds the MOV
  def valid_for?(cart)
    minimum_order_value.nil? || minimum_order_value < cart.item_sum
  end
end

app/models/shop_bunny/coupon_use.rb
class ShopBunny::CouponUse < ActiveRecord::Base
  belongs_to :cart
  belongs_to :coupon, :class_name => 'ShopBunny::Coupon'

  validates_presence_of :cart_id
  validates_presence_of :coupon_id
  validates_uniqueness_of :coupon_id, :scope => :cart_id
  validate :minimum_order_value_reached

  protected
  def minimum_order_value_reached
    errors.add(:base, :minimum_order_value) unless coupon.valid_for?(cart)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/shop_bunny/application_controller.rb
module ShopBunny
  class ApplicationController < ActionController::Base
    protect_from_forgery
  end
end

app/controllers/shop_bunny/carts_controller.rb
module ShopBunny
  class CartsController < ApplicationController
    include ShopBunny::CartControllerModule
  end
end

app/views/shop_bunny/carts/show.html.erb
<div class="shop">
  <h1>Shop</h1>
  <table>
    <table>
      <tr>
        <th>Item id</th>
        <th>Item price</th>
        <th>Action</th>
      </tr>
      <% @cart.item_model.limit(10).each do |item| %>
      <tr>
        <th><%= item.id %></th>
        <th><%= item.price %></th>
        <th id="<%= dom_id(item) %>"><%= link_to("Add to cart", add_item_to_cart_path(:item_id => item.id)) %></th>
      </tr>
      <% end %>
    </table>
  </table>
</div>

<div id="cart">
  <div class="items">
    <%= form_for @cart, :url => cart_path do |f| %>
      <h1>Shopping Cart</h1>
      <table>
        <tr>
          <th>Item id</th>
          <th>Item price</th>
          <th>Item quantity</th>
          <th>Remove</th>
        </tr>
    
        <%= f.fields_for :cart_items do |cart_item| %>
          <tr>
            <td><%= cart_item.object.item.id %></td>
            <td><%= cart_item.object.item.price %></td>
            <td><%= cart_item.text_field :quantity %></td>        
            <td><%= link_to "Remove item #{cart_item.object.item.id}", remove_item_from_cart_path(:item_id => cart_item.object.item.id) %></td>
          </tr>
        <% end %>
      </table>

      <table class="cashpoint">
        <tr>
          <td>Sum: <span id="price-item-sum"><%= number_to_currency @cart.item_sum %></span></td>
        </tr>
        <tr>
          <td>Shippin costs: <span id="price-shipping-costs"><%= number_to_currency @cart.shipping_costs %></span></td>
        </tr>
        <tr>
          <td>Total: <span id="price-total"><%= number_to_currency @cart.total %></span></td>
        </tr>
      </table>
  
      <%= f.submit %>
    <% end %>
  </div>

  <div class="coupons">
    <%= form_for @cart, :url => cart_path do |f| %>
      <h2>Your coupons</h2>
      <% if @cart.coupons.empty? %>
        No coupons added
      <% else %>
        <ul id="your_coupons">
        <% @cart.coupons.each do |coupon| %>
          <li><%= coupon.title %></ti>
        <% end %>
        </ul>
      <% end %>
      <ul id="error_messages">
      <% @cart.errors.full_messages.each do |err| %>
        <li><%= err %></li>
      <% end %>
      </ul>
      <%= f.label :coupon_code, 'Coupon code' %>
      <%= f.text_field :coupon_code %>
      <%= f.submit :value => "Add coupon" %>
    <% end %>
  </div>
</div>